### ISSUE TITLE
「プレイヤー体験のためのTRPGシナリオアンチパターン」アンチパターンを採用する際の補足強化について

### ISSUE THREAD

**Issue by stageleft** [Minori-Akizuki/trpg_notes#4]
掲題の文章について、総論賛成・各論賛成の立場から、論旨を強化するための補足が必要と認識する。詳細については以下。

* 心構えの記載強化、特にTRPGの本質・目的については章立てをしてでも明確化する。
  * 「TRPGというのはGMとプレイヤーが一体となってひとつの物語を作りあげるゲームである。」旨がアンチパターン集を作成する切っ掛けであり、論旨の本質である。
  * 補足として、TRPGはコミュニケーションを本質とするゲームであるがゆえに、TRPGの主役はプレイヤーであり、ルールやシナリオギミックは全て脇役であると心得る。例題の「まずくはないカレー」（何の変哲もないシナリオ）は、コミュニケーションの潤滑油として非常によく機能する、最高の調味料である。
  * TRPG動画についての弱点として、本質的にはプレイヤーが存在しないか、存在改変されている旨の指摘を明確化する必要がある。
* 全般の記載強化。
  * 「シナリオ説明で嘘を付く」：ゲーム内で「大惨事が起こる」こと自体は大きな問題ではない。ゲームの枠を超えて「プレイヤーが、GMあるいはシステムへの信頼を損なう」点が本質である。信頼関係を構築できないメンバーで会話を行うほどの苦痛は世の中にそうそう存在しない。
  * 「システムでサポートされていない秘匿ハンドアウト」：秘匿ハンドアウトがシステムでサポートされるべき理由を明言する。秘匿ハンドアウトは秘匿され続けることが良いのではなく、公開されたときに得られるカタルシスが本質であり、システムとシナリオによるサポートが絶対に必要である点を触れる。
  * 「キャラクターのロスト」：トーキョーN◎VAシリーズ、という例外についても触れる。同シリーズは格好良いロールプレイを至上としていることから、キャラクターの生命を賭した行動も推奨される範囲であり、当然キャラクターのロストは選択肢である。このため、システムとしてもキャラクターのロストがペナルティにならない工夫がなされている。ただし、この場合でも、キャラクターのロストは厳しい条件がある。１つは、キャラクターのロストは、キャラクターが大活躍した保証であること（プレイヤーが、キャラクターの喪失に対してポジティブに納得できること）。もう１つは、シナリオ最終盤であること（キャラクターのロスト後にプレイヤーが暇になってはならない）。例外を実現するハードルはかなり高いことを示し、改めてキャラクターのロストが禁忌である原則を納得させる。
* ストーリーについての補足
  * 「NPC無双」：NPCが強すぎてエネミーをなぎ倒してしまうこと自体は問題ではなく、それによりPCの立場が奪われることである。例えば、街を守るため強いNPCが来るまでの数瞬を稼ぐ、強いNPCを敵ボスまで無傷で届ける、といったような、強いNPCをサポートするようなシナリオも、「PCがいないと解決できなかった」という実感を持たせるには良いだろう。この場合、シナリオギミックとしては、強いNPCは「依頼人」の立場であり、PCと活躍の場を分ける描写は禁忌となる。
* 情報収集について、「重要に見える、無意味な情報の提示」アンチパターンが考えられる。「情報を点で出す」「情報の出し渋り」などと同様に、プレイヤーの混乱を招く元であるためである。混乱するべきはキャラクターでありプレイヤーではない。
* エネミー強化の方針について、「何かを無効にするエネミー」を出す場合の注意事項に漏れがある。「プレイヤーに対して、シナリオ開始前にその旨提示すること」が必要である。キャラクターの成長として、強化魔法等の活躍しづらい場でも貢献できる行動パターンを習得するなど、シナリオ開始前にプレイヤーへ対策させることが必要となる、の意味。

**Comment by stageleft** [comment]
https://twitter.com/elderalliance/status/1492685793533771779 での議論より、追加でのポイントについて、筆者様との議論結果を以下にサマリーする。

＜PCとPLの分離について＞
* PCとPLとの分離が明確でない可能性があり、議論を混乱させる原因となっている可能性がある（文章という個別の意味ではなく、全体的な議論として）。この点を補足すべきか検討いただく。
  * リプレイや動画視聴などでは、視点からしてPCとPLの分離は容易である。
  * 実卓では、PCとPLの分離は困難であり相当の経験が必要である。

＜本Issueについて＞
* 汎的な内容について、個々のシステムにまで踏み込む考察は厳しい。

**Comment by Minori-Akizuki** [comment]
@stageleft 
コメントうけて色々追記してみました。齟齬等ありましたら指摘願います。

**Comment by stageleft** [comment]
トーキョーN◎VAに関する例外について、こちら側の記載内容に、先入観による誤りがありました。 #4_antipattern ブランチへのPushもできなかったので、以下に差分提出します。
他の部分については、（コメント反映されなかった部分も含めて）いただいた記載内容にて問題ありません。

```diff
diff --git a/content/trpg_anti_pattern/_index.md b/content/trpg_anti_pattern/_index.md
index d71419f..4ac9896 100644
--- a/content/trpg_anti_pattern/_index.md
+++ b/content/trpg_anti_pattern/_index.md
@@ -120,9 +120,9 @@ TRPGというのはGMとプレイヤーが一体となってひとつの物語

 どんなシステムであろうと **キャラクターのロストはプレイヤーにとって最大の罰であり最悪の事態である** 事を忘れてはいけない。プレイヤーに故意かつ重大な過失がある、プレイヤー自身がそれを望んでいる、など特別な事 
情が無い限りキャラクターのロストは最大限に避けるべき事象である事を常々肝に命じておく事。

+一応。ロールプレイの一環としてキャラクターのロストを認めているシステムが存在する。例えば『トーキョー N◎VA』である。このシステムは「人が死にやすい世界観」にて「人が即死するようなスキルが飛び交う」中、「とにかくかっこいいロールプレイをする」という事を主軸にしているため、いよいよとなったらキャラクターのロストを視野に入れる事がシステムでサポートされている[^tnx]し、また、キャラクターを決してロストしないようなキャラクタービルドも容易となっている。先に言っておく。 **システムでサポートされているからギリギリ許されている** だけである事には留意していただきたい。
-一応。ロールプレイの一環としてキャラクターのロストを認めているシステムが存在する。例えば『トーキョー N◎VA』である。このシステムは「とにかくかっこいいロールプレイをする」という事を主軸にしているため、いよいよとなったらプレイヤーのロストを視野に入れる事がシステムでサポートされている。先に言っておく。 **システムでサポートされているからギリギリ許されている** だけである事には留意していただきたい。

+[^tnx]: 経験点はプレイヤーに属するため、キャラクターをロストすることによるプレイへの悪影響がないことが保証されている、程度の意味である。また、システムではないが、プレイヤーの操る「キャラクター同士の殺し合い」が発生しうる旨を、ルールブックの前書き部分に明記している。
-N◎VAのキャラロストにはきちんと条件もついている。「そのキャラクターのロストはキャラクターが最大限に活躍し(あるいはしようとした)結果である事」「セッションの終盤であること」。得に前者についてはその判定は厳しいものでなければならず、ただの自己犠牲や自殺行為では到底認められない。

 このようにロストを視野に入れる事のできるシステムですらそれは重大な判断であり例外である。そのぐらい **キャラクターのロストは禁忌** なのである。
```

**Comment by stageleft** [comment]
コメント反映ありがとうございました、本Issueについてはクローズ願います。
