### ISSUE TITLE
「TRPGにおけるマルチエンドシナリオの功績と原罪」を見て

### ISSUE THREAD

**Issue by kiniroroushi** [Minori-Akizuki/trpg_notes#6]
「TRPGにおけるマルチエンドシナリオの功績と原罪」を見て
https://kinniro.tea-nifty.com/system/2022/01/post-e65a68.html

**Comment by Minori-Akizuki** [comment]
[どうせルールブックすら読んでないあなたのための TRPG マルチルート/エンドシナリオの執筆法と回しかた](https://minori-akizuki.github.io/trpg_notes/howto_write_multiple_scenario/)
でそのあたりの事は補足しております。
あとissue切るならリンクではなく直接書いてくださいませ。
